name: default
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Export Dependabot alerts
        uses: ambilykk/dependabot-alert-export@v1.0
        with:
          GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
          org_name: 'Peter-Lankton'
          repo_name: 'twitter-clone-frontend'
          csv_path: data/vulnerability.csv

      - name: Upload Vulnerability report
        uses: actions/upload-artifact@v3
        with:
          name: vulnerability_report
          path: data/vulnerability.csv